@startuml GatherShadowDynamicMeshElements
start
    while(遍历所有阴影图图集 <color:#800080>ShadowMapAtlases</color>)
        while(遍历阴影图图集上的所有阴影实例)
            :收集它们需要投射阴影的网格元素 <color:#800080>GatherDynamicMeshElements</color>;
        endwhile
    endwhile

#HotPink:遍历所有RSM阴影图图集, 收集每个图集内的所有阴影实例的网格元素;
#HotPink:遍历所有点光源立方体阴影图, 收集每个立方体阴影图内的所有阴影实例的网格元素;
#HotPink:遍历所有PreShadow缓存的阴影图, 收集阴影实例的网格元素;
#HotPink:遍历所有透明物体阴影图图集, 收集每个图集内的所有阴影实例的网格元素;
end
@enduml