@startuml RenderDeferredShadowProjections
start

skinparam TitleBorderRoundCorner 15
skinparam TitleBorderColor Red
skinparam TitleBackgroundColor Aqua-Cadetblue

title 
    <size: 22>RenderDeferredShadowProjections
end title



end
@enduml 